### ISSUE TITLE
[Bug]: Event / Condition line deleted on displacement of those

### ISSUE THREAD

**Issue by MaelLF** [aica-technology/community#41]
### System configuration

![Image](https://github.com/user-attachments/assets/9c31f944-fdad-4dc8-823f-edd8abfa84c8)

### Brief description

**Graphical bug**: when on a long sequence (5+) moving an already attached (event/condition) can lead to their link disappearing. Doing the inverse movement or passing from graph to (3D/ROS TOPIC/LIVE TABLE) to graph again can make the link reappear.

### Steps to reproduce

Follow the steps in this video :

https://github.com/user-attachments/assets/fc5367a9-3156-49ea-ade2-931c8161196d

### Relevant log output

```Shell

```

### Supporting information

code : 
```
schema: 2-0-3
dependencies:
  core: v4.2.0
frames:
  one:
    reference_frame: world
    position:
      x: -0.598819
      y: 0.018378
      z: 0.315894
    orientation:
      w: 0.5167
      x: -0.200965
      y: -0.675061
      z: 0.486752
  two:
    reference_frame: world
    position:
      x: -0.509743
      y: 0.06812
      z: 0.444778
    orientation:
      w: -0.08044
      x: 0.569406
      y: 0.81744
      z: -0.033145
  three:
    reference_frame: world
    position:
      x: -0.549472
      y: 0.219355
      z: 0.45762
    orientation:
      w: 0.024549
      x: 0.726131
      y: -0.679252
      z: -0.103673
on_start:
  load:
    hardware: hardware
sequences:
  sequence:
    display_name: Starter
    steps:
      - delay: 5
      - switch_controllers:
          hardware: hardware
          activate: joint_trajectory_controller
      - sequence:
          start: sequence_3
  sequence_2:
    display_name: Trajectory on activate
    steps:
      - call_service:
          controller: joint_trajectory_controller
          hardware: hardware
          service: set_trajectory
          payload: "{frames: [one, two, three], times_from_start: [2.0,4.0,6.0]}"
  sequence_3:
    display_name: Trajectory  basic
    steps:
      - check:
          condition:
            controller: joint_trajectory_controller
            hardware: hardware
            predicate: has_trajectory_succeeded
          wait_forever: true
      - switch_controllers:
          hardware: hardware
          deactivate: joint_trajectory_controller
      - call_service:
          controller: joint_trajectory_controller
          hardware: hardware
          service: set_trajectory
          payload: "{frames: [two,three], times_from_start: [2.0,4.0]}"
      - check:
          condition:
            controller: joint_trajectory_controller
            hardware: hardware
            predicate: has_trajectory_succeeded
          wait_forever: true
      - load:
          component: tf_to_signal
      - load:
          component: signal_point_attractor
components:
  signal_point_attractor:
    component: aica_core_components::motion::SignalPointAttractor
    display_name: Signal Point Attractor
    events:
      predicates:
        is_in_range:
          application: stop
      transitions:
        on_load:
          lifecycle:
            component: signal_point_attractor
            transition: configure
        on_configure:
          lifecycle:
            component: signal_point_attractor
            transition: activate
    parameters:
      linear_precision: 0.1
    inputs:
      state: /hardware/robot_state_broadcaster/cartesian_state
      attractor: /tf_to_signal/pose
    outputs:
      twist: /signal_point_attractor/twist
  tf_to_signal:
    component: aica_core_components::ros::TfToSignal
    display_name: TF to Signal
    events:
      transitions:
        on_load:
          lifecycle:
            component: tf_to_signal
            transition: configure
          switch_controllers:
            hardware: hardware
            activate: ur_impedance_controller
        on_configure:
          lifecycle:
            component: tf_to_signal
            transition: activate
    parameters:
      frame: two
    outputs:
      pose: /tf_to_signal/pose
hardware:
  hardware:
    display_name: Hardware Interface
    urdf: Universal Robots 5e
    rate: 500
    events:
      transitions:
        on_load:
          load:
            - controller: robot_state_broadcaster
              hardware: hardware
            - controller: joint_trajectory_controller
              hardware: hardware
            - controller: ur_impedance_controller
              hardware: hardware
            - controller: ur_dashboard_controller
              hardware: hardware
    parameters:
      robot_ip: 192.168.56.101
      headless_mode: "False"
    controllers:
      robot_state_broadcaster:
        plugin: aica_core_controllers/RobotStateBroadcaster
        outputs:
          cartesian_state: /hardware/robot_state_broadcaster/cartesian_state
        events:
          transitions:
            on_load:
              switch_controllers:
                hardware: hardware
                activate: robot_state_broadcaster
      joint_trajectory_controller:
        plugin: aica_core_controllers/trajectory/JointTrajectoryController
        events:
          transitions:
            on_activate:
              sequence:
                start: sequence_2
      ur_impedance_controller:
        plugin: aica_ur_controllers/URImpedanceController
        parameters:
          force_limit:
            - !!float 10.0
            - !!float 10.0
            - !!float 10.0
            - !!float 1.0
            - !!float 1.0
            - !!float 1.0
          damping:
            - !!float 60.0
        inputs:
          command: /signal_point_attractor/twist
      ur_dashboard_controller:
        plugin: aica_ur_controllers/URDashboardController
        events:
          predicates:
            program_running:
              sequence:
                start: sequence
          transitions:
            on_load:
              switch_controllers:
                hardware: hardware
                activate: ur_dashboard_controller
graph:
  positions:
    on_start:
      x: 140
      y: -920
    stop:
      x: -60
      y: -280
    components:
      signal_point_attractor:
        x: 680
        y: 680
      tf_to_signal:
        x: -40
        y: 600
    hardware:
      hardware:
        x: 1120
        y: -900
    sequences:
      sequence:
        x: 180
        y: -620
      sequence_2:
        x: 1720
        y: 340
      sequence_3:
        x: -380
        y: -60
  edges:
    hardware_hardware_ur_dashboard_controller_program_running_hardware_hardware_joint_trajectory_controller:
      path:
        - x: 520
          y: 380
        - x: 520
          y: -240
    hardware_hardware_joint_trajectory_controller_has_trajectory_succeeded_sequence_3_sequence_3_condition_input_0:
      path:
        - x: 680
          y: 0
        - x: 680
          y: 280
        - x: 300
          y: 280
    hardware_hardware_joint_trajectory_controller_has_trajectory_succeeded_sequence_3_sequence_3_condition_input_2:
      path:
        - x: 860
          y: 0
        - x: 860
          y: 280
        - x: 660
          y: 280
    sequence_sequence_event_trigger_2_sequence_4_sequence_3:
      path:
        - x: 620
          y: -140
        - x: -20
          y: -140
        - x: -20
          y: 0
    hardware_joint_trajectory_controller_has_trajectory_succeeded_condition_sequence_2_sequence_3_condition_input_3:
      path:
        - x: 600
          y: -60
        - x: 600
          y: 220
        - x: 240
          y: 220
    sequence_2_sequence_2_event_trigger_3_hardware_hardware_joint_trajectory_controller:
      path:
        - x: 240
          y: 220
        - x: 680
          y: 220
        - x: 680
          y: -260
    sequence_2_sequence_3_event_trigger_3_hardware_hardware_joint_trajectory_controller:
      path:
        - x: 240
          y: 220
        - x: 680
          y: 220
        - x: 680
          y: -260
    on_start_on_start_hardware_hardware:
      path:
        - x: 620
          y: -880
        - x: 620
          y: -840
    sequence_sequence_event_trigger_1_hardware_hardware_joint_trajectory_controller:
      path:
        - x: 440
          y: -260
    sequence_sequence_event_trigger_2_sequence_3_sequence_3:
      path:
        - x: 620
          y: -180
        - x: -400
          y: -180
        - x: -400
          y: 0
    sequence_3_sequence_3_event_trigger_1_hardware_hardware_joint_trajectory_controller:
      path:
        - x: -120
          y: 220
        - x: 500
          y: 220
        - x: 500
          y: -260
    sequence_3_sequence_3_event_trigger_4_tf_to_signal_tf_to_signal:
      path:
        - x: 420
          y: 440
        - x: -80
          y: 440
        - x: -80
          y: 660
    sequence_3_sequence_3_event_trigger_5_signal_point_attractor_signal_point_attractor:
      path:
        - x: 600
          y: 740
    sequence_2_sequence_2_event_trigger_0_hardware_hardware_joint_trajectory_controller_set_trajectory:
      path:
        - x: 1800
          y: 20
    hardware_joint_trajectory_controller_has_trajectory_succeeded_condition_sequence_3_sequence_3_condition_input_0:
      path:
        - x: 680
          y: -60
        - x: 680
          y: 240
        - x: -300
          y: 240
    sequence_3_sequence_3_event_trigger_2_hardware_hardware_joint_trajectory_controller_set_trajectory:
      path:
        - x: 60
          y: 280
        - x: 760
          y: 280
        - x: 760
          y: 20
    hardware_joint_trajectory_controller_has_trajectory_succeeded_condition_sequence_3_sequence_3_condition_input_3:
      path:
        - x: 600
          y: -60
        - x: 600
          y: 220
        - x: 240
          y: 220
    signal_point_attractor_is_in_range_on_stop_on_stop:
      path:
        - x: 1200
          y: 900
        - x: 1200
          y: 300
        - x: -80
          y: 300
        - x: -80
          y: -240
    tf_to_signal_on_load_hardware_hardware_ur_impedance_controller:
      path:
        - x: 720
          y: 780
        - x: 720
          y: 160
    hardware_hardware_joint_trajectory_controller_on_activate_sequence_2_sequence_2:
      path:
        - x: 960
          y: -140
        - x: 960
          y: 400
    hardware_hardware_ur_dashboard_controller_program_running_sequence_sequence:
      path:
        - x: 160
          y: 540
        - x: 160
          y: -560
    hardware_hardware_robot_state_broadcaster_cartesian_state_signal_point_attractor_state:
      path:
        - x: 760
          y: -360
        - x: 760
          y: 660
        - x: 640
          y: 660
        - x: 640
          y: 980
    tf_to_signal_pose_signal_point_attractor_attractor:
      path:
        - x: 600
          y: 860
        - x: 600
          y: 1020
    signal_point_attractor_twist_hardware_hardware_ur_impedance_controller_command:
      path:
        - x: 1100
          y: 980
        - x: 1100
          y: 320
```
